import { ILlmInferenceProvider } from "../../Infrastructure/Inference/ILlmInferenceProvider";
import { ILogger } from "../../Infrastructure/Logging/ILogger";
import { IJobPostRepository } from "../../Infrastructure/Persistence/JobPost/IJobPostRepository";
import { SqliteDatabaseConnection } from "../../Infrastructure/Persistence/JobPost/Sqlite/SqliteDatabaseConnection";
import { IJobSourceRepository } from "../../Infrastructure/Persistence/JobSource/IJobSourceRepository";
import { IJobAssessmentQueue } from "../../Infrastructure/Persistence/Queues/JobAssessmentQueue/IJobAssessmentQueue";
import { IJobPostSyncQueue } from "../../Infrastructure/Persistence/Queues/JobPostSyncQueue/IJobPostSyncQueue";
import { IJobApplicationService } from "../JobApplications/IJobApplicationService";
import { IJobAssessmentService } from "../JobAssessment/IJobAssessmentService";
import { IJobAssessmentQueueService } from "../JobAssessment/PipelineQueue/IJobAssessmentQueueService";
import { IJobAssessmentQueueWorkerService } from "../JobAssessment/PipelineQueue/IJobAssessmentQueueWorkerService";
import { IJobRequirementsMatchingService } from "../JobAssessment/RequirementMatching/IJobRequirementMatchingService";
import { IJobRequirementsExtractionService } from "../JobAssessment/RequirementsExtraction/IJobRequirementsExtractionService";
import { IJobScreeningService } from "../JobAssessment/Screening/IJobScreeningService";
import { IJobCandidateProfileService } from "../JobCandidateProfiles/IJobCandidateProfileService";
import { IJobPostResultTableService } from "../JobPost/IJobPostResultTableService";
import { IJobPostService } from "../JobPost/IJobPostService";
import { IJobPostDiscoveryServiceFactory } from "../JobPostDiscovery/IJobPostDiscoveryServiceFactory";
import { IJobPostSyncService } from "../JobPostSync/IJobPostSyncService";
import { IJobPostSyncDailySchedulerService } from "../JobPostSync/Queue/IJobPostSyncDailySchedulerService";
import { IJobPostSyncQueueService } from "../JobPostSync/Queue/IJobPostSyncQueueService";
import { IJobPostSyncQueueWorkerService } from "../JobPostSync/Queue/IJobPostSyncQueueWorkerService";
import { IJobSourceService } from "../JobSources/IJobSourceService";

export interface IApplicationDependencies {
    jobAssessmentService: IJobAssessmentService;
    logger: ILogger;
    sqliteConnection: SqliteDatabaseConnection;
    jobPostRepository: IJobPostRepository;
    jobSourceRepository: IJobSourceRepository;
    jobPostResultService: IJobPostResultTableService;
    jobPostSyncService: IJobPostSyncService;
    jobPostSyncQueue: IJobPostSyncQueue;
    jobPostSyncQueueService: IJobPostSyncQueueService;
    jobPostSyncDailySchedulerService: IJobPostSyncDailySchedulerService;
    jobPostService: IJobPostService;
    jobAssessmentQueue: IJobAssessmentQueue;
    jobAssessmentQueueService: IJobAssessmentQueueService;
    jobPostSyncQueueWorkerService: IJobPostSyncQueueWorkerService;
    jobCandidateProfileService: IJobCandidateProfileService;
    jobSourceService: IJobSourceService;
    inferenceProvider: ILlmInferenceProvider;
    screeningService: IJobScreeningService;
    requirementsExtractionService: IJobRequirementsExtractionService;
    requirementsMatchingService: IJobRequirementsMatchingService;
    jobPostDiscoveryServiceFactory: IJobPostDiscoveryServiceFactory;
    jobAssessmentQueueWorkerService: IJobAssessmentQueueWorkerService;
    jobApplicationService: IJobApplicationService;
}
